/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface OCRText {
  x: number
  y: number
  width: number
  height: number
  text: string
}
export type JsScreenshot = Screenshot
export class Screenshot {
  constructor(windowStr?: string | undefined | null, subWindowStr?: string | undefined | null, shadowTextLib?: string | undefined | null)
  distory(): void
  take(left: number, top: number, right: number, bottom: number): Buffer
  takeBmp(left: number, top: number, right: number, bottom: number): Buffer
  dhOcrShadowText(left: number, top: number, right: number, bottom: number, simlar: number, row: number, col: number): Array<OCRText>
}
